/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EstudioRouteImport } from './routes/estudio'
import { Route as PromocionesRouteImport } from './routes/promociones'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EstudioRoute = EstudioRouteImport.update({
  id: '/estudio',
  path: '/estudio',
  getParentRoute: () => rootRouteImport,
} as any)
const PromocionesRoute = PromocionesRouteImport.update({
  id: '/promociones',
  path: '/promociones',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/estudio': typeof EstudioRoute
  '/promociones': typeof PromocionesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/estudio': typeof EstudioRoute
  '/promociones': typeof PromocionesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/estudio': typeof EstudioRoute
  '/promociones': typeof PromocionesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/estudio' | '/promociones'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/estudio' | '/promociones'
  id: '__root__' | '/' | '/estudio' | '/promociones'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EstudioRoute: typeof EstudioRoute
  PromocionesRoute: typeof PromocionesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estudio': {
      id: '/estudio'
      path: '/estudio'
      fullPath: '/estudio'
      preLoaderRoute: typeof EstudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promociones': {
      id: '/promociones'
      path: '/promociones'
      fullPath: '/promociones'
      preLoaderRoute: typeof PromocionesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EstudioRoute: EstudioRoute,
  PromocionesRoute: PromocionesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
